export const StyledConfig = {
  checkbox: {
    sm: {
      fs: "14px",
      h: "14px",
      w: "14px",
      mh: "8px",
      mw: "3px",
      m: "0px 0px 0px 4px",
    },
    md: {
      fs: "18px",
      h: "18px",
      w: "18px",
      mh: "10px",
      mw: "5px",
      m: "1px 0px 0px 5px",
    },
    lg: {
      fs: "20px",
      h: "22px",
      w: "22px",
      mh: "16px",
      mw: "8px",
      m: "0px 0px 0px 5px",
    },
    xl: {
      fs: "24px",
      h: "26px",
      w: "26px",
      mh: "20px",
      mw: "11px",
      m: "0px 0px 4px 6px",
    },
  },
  radio: {
    sm: {
      p: "5px 0px 0px 3px",
      fs: "14px",
      b: "2px",
      h: "8px",
      w: "8px",
    },
    md: {
      p: "6px 0px 0px 3px",
      fs: "16px",
      b: "3px",
      h: "12px",
      w: "12px",
    },
    lg: {
      p: "8px 0px 0px 3px",
      fs: "18px",
      b: "4px",
      h: "16px",
      w: "16px",
    },
    xl: {
      p: "10px 0px 0px 3px",
      fs: "20px",
      b: "5px",
      h: "20px",
      w: "20px",
    },
  },
  toggle: {
    sm: {
      w: 40,
      h: 20,
      cw: 0.9,
      ch: 0.9,
      left: 1.2,
    },
    md: {
      w: 45,
      h: 23,
      cw: 1.1,
      ch: 1.1,
      left: 1.3,
    },
    lg: {
      w: 52,
      h: 27,
      cw: 1.3,
      ch: 1.3,
      left: 1.5,
    },
    xl: {
      w: 59,
      h: 31,
      cw: 1.5,
      ch: 1.5,
      left: 1.7,
    },
  },
  input: {
    sm: {
      pr: 25,
      pt: 5,
      fs: 0.9,
    },
    md: {
      pr: 30,
      pt: 7,
      fs: 1.2,
    },
    lg: {
      pr: 35,
      pt: 7,
      fs: 1.5,
    },
    xl: {
      pr: 40,
      pt: 8,
      fs: 1.8,
    },
  },
};
